import { Injectable } from '@angular/core';
import { ConexionService } from './conexion.service';
import { ConsumoAPIService } from './consumo-api.service';

@Injectable({
  providedIn: 'root'
})
export class MateriasService {
  firebd: any;
  matri2:any=  [
    ["5101", 'MATEMÁTICAS DISCRETAS '],
    ["5102", 'ALGEBRA LINEAL '],
    ["5103", 'FUNDAMENTOS DE COMPUTACIÓN '],
    ["5104", 'ALGORITMOS Y LOGICA COMPUTACIONAL '],
    ["5105", 'LABORATORIO ALGORITMOS Y LOGICA COMPUTACIONAL'],
    ["5106", 'COMPRENCIÓN Y PRODUCCION DE TEXTOS '],
    ["5107", 'ADMINISTRACIÓN Y CONTABILIDAD '],
    ["5208", 'CÁLCULO DIFERENCIAL E INTEGRAL'],["5209", 'ARQUITECTURA DE COMPUTADORAS '],["5210", 'COMPRENSION Y PRODUCCION DE TEXTOS EN INGLES'],
    ["5211", 'PROGRAMACION I'],["5212", 'LABORATORIO DE PROGRAMACIÓN I'],["5213", 'SISTEMAS OPERATIVOS'],
    ["5214", 'LABORATORIO DE SISTEMAS OPERATIVOS'],["5215", 'COSTOS'],["5316", 'TEORÍA DE LA COMPUTACIÓN'],
    ["5317", 'ARQUITECTURA DE COMPUTADORAS II'],["5318", 'LABORATORIO DE ARQUITECTURA DE COMPUTADORAS II'],["5319", 'ESTRUCTURA DE DATOS'],
    ["5320", 'LABORATORIO DE ESTRUCTURA DE DATOS'],["5321", 'PROGRAMACIÓN II'],["5322", 'LABORATORIO DE PROGRAMACIÓN II'],
    ["5323", 'PROBABILIDAD Y ESTADISTICA'],["5324", 'VALORES Y ÉTICA PROFECIONAL'],["5425", 'INVESTIGACION Y OPERACIONES'],
    ["5426", 'INGENIERIA DE SOFTWARE I'],["5427", 'REDES I'],["5428", 'LABORATORIO DE REDES I'],
    ["5429", 'PROGRAMACION ORIENTADA A OBJETOS'],["5430", 'LABORATORIO DE PROGRAMACION ORIENTADA A OBJETOS'],["5431", 'FUNDAMENTO DE BASE DE DATOS'],
    ["5432", 'LABORATORIO FUNDAMENTOS DE BASE DE DATOS'],["5433", 'SISTEMAS DIGITALES'],["5534", 'INGENIERÍA ECONÓMICA'],
    ["5535", 'INGENIERÍA DE SOFTWARE II'],["5536", 'REDES II'],["5537", 'LABORATORIO DE REDES II'],
    ["5538", 'LENGUAJES DE PROGRAMACIÓN'],["5539", 'LABORATORIO LENGUAJES DE PROGRAMACION'],["5540", 'BASES DE DATOS DISTRIBUIDAS'],
    ["5541", 'LABORATORIO BASES DE DATOS DISTRIBUIDAS'],["5542", 'METODOLOGÍA DE LA INVESTIGACIÓN'],["5643", 'SISTEMA DE INFORMACIÓN'],
    ["5644", 'DESARROLLO DE APLICACIONES WEB I'],["5645", 'LABORATORIO DESARROLLO DE APLICACIONES WEB I'],["5646", 'INTERACCCIÓN HUMANO COMPUTADORA'],
    ["5647", 'LABORATORIO INTERACCIÓN HUMANO COMPUTADORA'],["5649", 'ADMINISTRACIÓN DE PROYECTOS DE SOFTWARE I'],["5650", 'LABORATORIO ADMINISTRACIÓN DE PROYECTOS DE SOFTWARE I'],
    ["5651", 'ADMINISTRACIÓN DE SISTEMAS'],["5652", 'LABORATORIO ADMINISTRACIÓN DE SISTEMAS'],["5753", 'SOFTWARE DE SISTEMAS'],
    ["5754", 'DESARROLLO DE APLICACIONES WEB II'],["5755", 'LABORATORIO DESARROLLO DE APLICACIONES WEB II'],["5756", 'SISTEMAS DE APOYO A LA TOMA DE DECISIONES '],
    ["5757", 'ADMINISTRACIÓN DE PROYECTOS DE SOFTWARE II'],["5758", 'LABORATORIO ADMINISTRACIÓN DE PROYECTOS DE SOFTWARE'],["5759", 'MODELADO DE PROCESOS'],

  ];
  /*matri:any=  [
    ["0101", 'UNA MATERIA '], ["0102", 'UNA MATERIA '], ["0103", 'UNA MATERIA '],
    ["0104", 'UNA MATERIA '], ["0105", 'UNA MATERIA '], ["1106", 'UNA MATERIA '],
    ["1107", 'UNA MATERIA '], ["1108", 'UNA MATERIA '], ["1109", 'UNA MATERIA '],
    ["1110", 'UNA MATERIA '], ["2111", 'UNA MATERIA '], ["2112", 'UNA MATERIA '],
    ["2114", 'UNA MATERIA '], ["2115", 'UNA MATERIA '], ["3116", 'UNA MATERIA '],
  ];*/
  matri:any = []
  constructor(private conect:ConexionService, private API: ConsumoAPIService) { 
    this.firebd = this.conect.getstore(); 
  }
getmat(plan: any, carrera: any){
  this.API.obtenerMateria(plan, carrera).subscribe((res:any)=>{
    console.log(res)
    this.matri2 = res;
  },(e)=>{
  });
}
  getmatri(){
    return this.matri2;
    }
}
